# Generated by Django 4.1.2 on 2022-11-24 02:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsdb", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="id",
        ),
        migrations.AlterField(
            model_name="job",
            name="job_files",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(), size=None
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="uuid",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
