# Generated by Django 4.1.2 on 2022-11-07 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsdb", "0002_remove_job_id_alter_job_job_files_alter_job_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_files",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), size=None
            ),
        ),
    ]
