# Generated by Django 4.1.2 on 2022-10-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsdb", "0003_alter_job_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="uuid",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
