# Generated by Django 4.1.2 on 2022-10-24 16:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobsdb", "0005_alter_job_job_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_files",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=150), size=None
            ),
        ),
    ]
